- name: Check Dahua NVR firmware version
  hosts: dahua
  tasks:
    - name: Call Dahua NVR API to get firmware version
      uri:
        url: http://{{ inventory_hostname }}/cgi-bin/system.cgi?action=getSysInfo
        method: GET
        user: admin
        password: 'Nr!?@#$945'  # Replace with your actual credentials
        force_basic_auth: no
        return_content: yes
      register: result

    - name: Print the firmware version
      debug:
        var: result.content