- name: Ping CentOS, Ubuntu and Windows nodes
  hosts: all
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
  tasks:
    - name: Ping CentOS hosts
      block:
        - name: Ping CentOS hosts
          ping: 
      #when: ansible_connection =='ssh'
      when: ansible_distribution == 'CentOS'
      tags:
        - centos

    - name: Ping Ubuntu hosts
      block:
        - name: Ping CentOS hosts
          ping:
      #when: ansible_connection =='ssh'
      when: ansible_distribution == 'Ubuntu'
      tags:
        - ubuntu

    - name: Ping Windows hosts
      block:
        - name: Ping CentOS hosts
          win_ping:
      when: ansible_connection == 'winrm'
      tags:
        - windows
