- name: Manage Windows hosts
  hosts: windows
  gather_facts: no

  tasks:

    - name: Ping Windows node
      win_ping:

    - name: List C:\ directory safely
      win_command: cmd.exe /c dir C:/
      register: dir_output
      ignore_errors: yes    # allow command to fail without crashing playbook

    - name: Check if listing succeeded
      debug:
        msg: "Directory listing successful!"
      when: dir_output.rc == 0

    - name: Handle listing failure
      debug:
        msg: "Directory listing FAILED: {{ dir_output.stderr }}"
      when: dir_output.rc != 0

    - name: Always run this task
      debug:
        msg: "Finished directory handling tasks."
