- name: Manage Windows hosts
  hosts: windows
  gather_facts: no
  tasks:
    - name: Ping
      win_ping:

    - name: List directory
      win_command: cmd.exe /c dir C:\
      register: dir_output

    #- name: Run dir C:\ using win_shell
      #win_shell: dir C:\
      #register: dir_output

    - name: Show output of dir C:\
      debug:
        var: dir_output.stdout_lines