- name: Manage Linux hosts
  hosts: ubuntu
  gather_facts: yes
  tasks:
    - name: Ping
      ping:

    - name: Check uptime
      command: uptime
      register: uptime_output

    - name: Show uptime of ubuntu
      debug:
        var: uptime_output.stdout_lines