# This is a playbook to ping Linux and Windows hosts
- name: Ping all hosts
  hosts: all
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  tasks:
    - name: Ping Linux systems
      ping:
      when: ansible_os_family != "Windows"  # Skip this task on Windows
      
    - name: Ping Windows systems
      win_ping:
      when: ansible_os_family == "Windows"  # Run only on Windows