- name: Manage Windows hosts
  hosts: windows
  gather_facts: no

  tasks:
    - name: Ping Windows node
      win_ping:

- name: Try directory listing
  block:

    - name: List C:\ directory
      win_command: cmd.exe /c dir C:/
      register: dir_output
      failed_when: false    # force Ansible to think this task never fails

    - name: Debug success
      debug:
        msg: "Directory listing succeeded!"
      when: dir_output.rc == 0

    - name: Debug failure
      debug:
        msg: "Directory listing FAILED: {{ dir_output.stderr }}"
      when: dir_output.rc != 0
